# Generated by Django 3.0.6 on 2020-06-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20200614_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booknumber',
            old_name='isbn_12',
            new_name='isbn_13',
        ),
    ]
